default:
  image: docker:stable

build-job:
  stage: build
  script:
    - systemctl start docker
    - docker build -t lchanif/cicd-test .

test-job:
  stage: test
  script:
    - echo "This job tests something"

deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
    - docker push lchanif/cicd-test
