default:
  image: centos:latest
build-job:
  stage: build
  script:
    - sudo docker build -t lchanif/cicd-test .

fake-test:
  stage: test
  script:
    - echo "This job tests something"

deploy:
  stage: Push to Docker Hub
  only:
    - master
  script:
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
    - docker push lchanif/cicd-test
