default:
  image: centos:latest
build-job:
  stage: build
  script:
    - sudo docker build -t lchanif/cicd-test .

test-job:
  stage: test
  script:
    - echo "This job tests something"

deploy-prod:
  stage: Push to Docker Hub
  only:
    - master
  script:
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
    - docker push lchanif/cicd-test
