image: docker:latest
services:
  - docker:dind

build-job:
  stage: build
  script:
    - docker build -t lchanif/cicd-test .
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
    - docker push lchanif/cicd-test

#test-job:
 # stage: test
  #script:
   # - docker pull lchanif/cicd-test:latest
    #- docker build lchanif/cicd-test:latest

#deploy-prod:
#  stage: deploy
#  only:
#    - main
#  script:
#    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
#    - docker push lchanif/cicd-test

### Testing if webhooks work 
